"""Add UserStatistic.total_games

Revision ID: 25217ae0199d
Revises: a7e945dccd06
Create Date: 2025-07-06 10:21:07.540227

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '25217ae0199d'
down_revision: Union[str, None] = 'a7e945dccd06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('table_user_statistic', sa.Column('total_games', sa.Integer(), server_default='0', nullable=False, comment='Общее количество игр'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('table_user_statistic', 'total_games')
    # ### end Alembic commands ###
