"""Init

Revision ID: a7e945dccd06
Revises:
Create Date: 2025-06-03 09:40:13.080772

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a7e945dccd06'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'table_image',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
        sa.Column('id_telegram', sa.String(length=128), nullable=False, comment='id в Telegram'),
        sa.Column('id_telegram_rotated', sa.String(length=128), server_default=sa.text('NULL'), nullable=True, comment='id в Telegram (перевернутое)'),
        sa.Column('local_path', sa.String(length=128), nullable=False, comment='путь'),
        sa.Column('name', sa.String(length=48), nullable=False, comment='название'),
        sa.Column('category', sa.Integer(), nullable=False, comment='категория'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id_telegram'),
        sa.UniqueConstraint('id_telegram_rotated'),
        sa.UniqueConstraint('local_path'),
        sa.UniqueConstraint('name'),
        comment='Изображение',
    )
    op.create_table(
        'table_user',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
        sa.Column('datetime_start', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='дата и время старта бота'),
        sa.Column('datetime_stop', sa.DateTime(timezone=True), server_default=sa.text('NULL'), nullable=True, comment='дата и время остановки бота'),
        sa.Column('id_telegram', sa.String(length=17), nullable=False, comment='id в Telegram'),
        sa.Column('message_main_last_id', sa.Integer(), server_default=sa.text('NULL'), nullable=True, comment='id последнего сообщения "Главная"'),
        sa.Column('name_first', sa.String(length=64), server_default=sa.text('NULL'), nullable=True, comment='имя'),
        sa.Column('name_last', sa.String(length=64), server_default=sa.text('NULL'), nullable=True, comment='фамилия'),
        sa.Column('username', sa.String(length=32), server_default=sa.text('NULL'), nullable=True, comment='username в Telegram'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('id_telegram'),
        comment='Пользователь',
    )
    op.create_table(
        'table_user_achievement',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
        sa.Column('dream_master', sa.Integer(), server_default='0', nullable=False, comment='Cон на яву'),
        sa.Column('nightmare', sa.Integer(), server_default='0', nullable=False, comment='Cущий кошмар'),
        sa.Column('top_penalties', sa.Integer(), server_default='0', nullable=False, comment='Кайфоломщик'),
        sa.Column('top_score', sa.Integer(), server_default='0', nullable=False, comment='Высший разум'),
        sa.Column('top_score_buka', sa.Integer(), server_default='0', nullable=False, comment='Бу-бу-бука'),
        sa.Column('top_score_fairy', sa.Integer(), server_default='0', nullable=False, comment='Крестная фея'),
        sa.Column('top_score_sandman', sa.Integer(), server_default='0', nullable=False, comment='Лицемерище'),
        sa.Column('top_score_dreamer', sa.Integer(), server_default='0', nullable=False, comment='Яркие сны'),
        sa.Column('user_id', sa.Integer(), nullable=False, comment='ID пользователя'),
        sa.ForeignKeyConstraint(['user_id'], ['table_user.id'], name='table_user_achievement_table_user_fkey', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id'),
        comment='Достижения пользователей',
    )
    op.create_table(
        'table_user_statistic',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='ID'),
        sa.Column('last_game_datetime', sa.DateTime(timezone=True), server_default=sa.text('NULL'), nullable=True, comment='Дата и время последней игры'),
        sa.Column('top_penalties', sa.Integer(), server_default='0', nullable=False, comment='Общее количество штрафов'),
        sa.Column('total_quits', sa.Integer(), server_default='0', nullable=False, comment='Общее количество выходов из игры'),
        sa.Column('top_score', sa.Integer(), server_default='0', nullable=False, comment='Общее количество очков'),
        sa.Column('top_score_buka', sa.Integer(), server_default='0', nullable=False, comment='Общее количество очков за буку'),
        sa.Column('top_score_dreamer', sa.Integer(), server_default='0', nullable=False, comment='Общее количество очков за сновидца'),
        sa.Column('top_score_fairy', sa.Integer(), server_default='0', nullable=False, comment='Общее количество очков за фею'),
        sa.Column('top_score_sandman', sa.Integer(), server_default='0', nullable=False, comment='Общее количество очков за песочного человека'),
        sa.Column('total_wins', sa.Integer(), server_default='0', nullable=False, comment='Общее количество побед'),
        sa.Column('user_id', sa.Integer(), nullable=False, comment='ID пользователя'),
        sa.ForeignKeyConstraint(['user_id'], ['table_user.id'], name='table_user_statistic_table_user_fkey', ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('user_id'),
        comment='Статистика пользователей',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('table_user_statistic')
    op.drop_table('table_user_achievement')
    op.drop_table('table_user')
    op.drop_table('table_image')
    # ### end Alembic commands ###
