name: When I Dream Bot (main)

on:
  push:
    branches:
      - main

jobs:

  run_project_tests:
    name: Run tests for Project
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12",]
    steps:
      - name: Clone Project to runner
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r ./app/requirements.txt
          pip install pytest
      - name: Run Pytest
        run: |
          cd ./app
          pytest

  build_and_push_project_image:
    name: Build Project image and push to the DockerHub
    needs:
      - run_project_tests
    runs-on: ubuntu-latest
    steps:
      - name: Clone Project to runner
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push Project image to the Dockerhub
        uses: docker/build-push-action@v5
        with:
          context: ./app/
          push: True
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/when_i_dream_bot:latest

  deploy_project_on_server:
    name: Deploy Project on server
    needs: build_and_push_project_image
    runs-on: ubuntu-latest
    steps:
      - name: Clone Project to runner
        uses: actions/checkout@v4
      - name: Copy docker-compose.yml to server via ssh
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          source: "docker/docker-compose.yml"
          target: "/home/kirill/when_i_dream_bot/"
          strip_components: 1
      - name: Executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          password: ${{ secrets.SSH_PASSWORD }}
          script: |
            cd /home/kirill/when_i_dream_bot
            docker compose down
            docker image rm ${{ secrets.DOCKERHUB_USERNAME }}/when_i_dream_bot
            docker compose up -d

  send_message_telegram:
    name: Send message to telegram
    needs: deploy_project_on_server
    runs-on: ubuntu-latest
    steps:
      - name: Send message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_ME_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: Деплой "@When_I_Dream_Bot" выполнен успешно!
